apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: frontend
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: username  
        - name: ME_CONFIG_BASICAUTH_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password     
        ports:
        - containerPort: 8081
          name: mongoexpress
        volumeMounts:
        - name: mongoexpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: mongoexpress-persistent-storage
        persistentVolumeClaim:
          claimName: mongoexpress-pv-claim
